"""
Generated by `elyaeval init --task-type rag_qa`.

This file is yours to edit — it is a starting point, not a managed
artifact. Everything below calls DeepEval's own API directly (evaluate,
LLMTestCase, Golden). ElyaEval supplied the dataset and the metric preset.

WHAT YOU NEED TO FILL IN (search for TODO):
  1. Import your app's entrypoint function.
  2. Implement run_app() to call it and return (actual_output, retrieval_context).
  3. Implement _ingest_passage / _teardown_passages so retrieval-dependent
     metrics have something relevant to retrieve (see make_golden_context_fixture).
"""

import os

import psycopg2
import pytest
from deepeval import assert_test
from deepeval.test_case import LLMTestCase

from elyaeval import load_standard_dataset, make_golden_context_fixture
from elyaeval.metrics import RAG_METRICS

# TODO 1: import your app under test, e.g.:
# from myapp.pipeline import answer_question
from rag_core import run_for_eval
from ingest import chunk_text
from embeddings import embed_text


def run_app(user_input: str, expected_output: str | None = None) -> tuple[str, list[str]]:
    """
    TODO 2: Call your own app here.

    Must return (actual_output, retrieval_context):
      - actual_output: the final string your app returns for `user_input`.
      - retrieval_context: the list of chunk strings your app's retriever
        fetched while answering. This is intentionally NOT provided by
        ElyaEval's dataset—only your app knows what it retrieved.

    Example:
        result = answer_question(user_input)
        return result.answer, result.retrieved_chunks
    """
    result = run_for_eval(user_input,expected_output= expected_output)
    return result["answer"], result["retrieval_context"]


GOLDENS = load_standard_dataset(task_type="rag_qa", ci_stage="nightly")


# --- TODO 3: golden-context ingest/teardown -------------------------------
# The goldens above come with their own `context` passages,
# unrelated to whatever your app's real corpus already contains. Without
# seeding them in first, retrieval will find your app's *real* documents —
# plausible-looking, but never a match for what the golden actually asks.

# DATABASE_URL below matches the same env var retriever.py uses.
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://raguser:ragpass@localhost:5432/ragdb")


def _ingest_passage(passage: str) -> list[int]:
    """Chunk + embed + insert one golden passage. Returns the row ids
    inserted, so teardown can delete exactly these rows and nothing else —
    no dependency on a source/tag column existing in the schema."""
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()
    row_ids = []
    for chunk in chunk_text(passage):
        cur.execute(
            "INSERT INTO rag_demo_chunks (source, content, embedding) VALUES (%s, %s, %s) RETURNING id",
            ("golden_context", chunk, embed_text(chunk)),
        )
        row_ids.append(cur.fetchone()[0])
    conn.commit()
    cur.close()
    conn.close()
    return row_ids


def _teardown_passages(handles: list[list[int]]) -> None:
    """Delete exactly the rows whose ids were returned by _ingest_passage."""
    all_ids = [row_id for ids in handles for row_id in ids]
    if not all_ids:
        return
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()
    cur.execute("DELETE FROM rag_demo_chunks WHERE id = ANY(%s)", (all_ids,))
    conn.commit()
    cur.close()
    conn.close()


ingest_golden_contexts = make_golden_context_fixture(GOLDENS, _ingest_passage, _teardown_passages)
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "golden",
    GOLDENS,
    ids=[g.additional_metadata.get("priority", "") + "_" + str(i) for i, g in enumerate(GOLDENS)],
)
def test_rag_qa(golden):
    run_app(golden.input, expected_output=golden.expected_output)
    assert_test(golden=golden)

    test_case = LLMTestCase(
        input=golden.input,
        actual_output=actual_output,
        expected_output=golden.expected_output,
        context=golden.context,
        retrieval_context=retrieval_context,
    )

    assert_test(test_case, RAG_METRICS)