"""
Generated by `elyaeval init --task-type rag_qa`.

This file is yours to edit — it is a starting point, not a managed
artifact. Everything below calls DeepEval's own API directly (evaluate,
LLMTestCase, Golden). ElyaEval supplied the dataset and the metric preset.

EXISTING-CORPUS mode (the default): this suite assumes your app's corpus
already has content relevant to GOLDENS below, so it just calls run_app()
and lets your app retrieve normally — nothing is inserted or removed from
your storage.

The bundled standard dataset is a generic, cross-app benchmark — it is
almost never a corpus match for YOUR app. For this mode to produce
meaningful retrieval-dependent scores (ContextualPrecision/Recall/
Relevancy, Faithfulness), point GOLDENS at your own goldens file instead,
written against what's really in your corpus:

    GOLDENS = load_standard_dataset(
        task_type="rag_qa", ci_stage="nightly",
        dataset_path="path/to/your_goldens.jsonl",
    )

Only reach for the shared dataset + a temporary seed/teardown of its
`context` passages when you deliberately want to run the generic
benchmark against an app whose corpus doesn't already cover it (e.g. a
throwaway CI corpus). That's a different, opt-in generator:

    elyaeval init --task-type rag_qa --corpus-mode seeded

WHAT YOU NEED TO FILL IN (search for TODO):
  1. Import your app's entrypoint function.
  2. Implement run_app() to call it and return (actual_output, retrieval_context).

REPORT_CSV: each golden's per-metric scores (name/score/threshold/success/
reason) are appended to this CSV as they run — one row per metric, so you
can filter/sort by metric or golden afterward instead of reading raw
pytest/junit output. Point it at wherever your CI workspace collects
reports; it defaults to a local report/ dir for running the suite by hand.
"""

from pathlib import Path

from deepeval.test_case import LLMTestCase
import pytest

from elyaeval import load_standard_dataset, evaluate_golden, new_report_path
from elyaeval.metrics import RAG_METRICS

REPORT_CSV = new_report_path("rag_qa")

import os
import requests

APP_URL = os.environ.get("APP_URL", "http://localhost:8000")


def run_app(user_input: str) -> tuple[str, list[str]]:
    resp = requests.post(f"{APP_URL}/query", json={"query": user_input})
    resp.raise_for_status()
    data = resp.json()
    return data["answer"], data["retrieval_context"]


GOLDENS = load_standard_dataset(
    task_type="rag_qa", ci_stage="nightly",
    dataset_path="goldens_rag_demo.jsonl",
)


@pytest.mark.parametrize(
    "indexed_golden",
    list(enumerate(GOLDENS)),
    ids=[g.additional_metadata.get("priority", "") + "_" + str(i) for i, g in enumerate(GOLDENS)],
)
def test_rag_qa(indexed_golden):
    index, golden = indexed_golden
    actual_output, retrieval_context = run_app(golden.input)

    test_case = LLMTestCase(
        input=golden.input,
        actual_output=actual_output,
        expected_output=golden.expected_output,
        context=golden.context,
        retrieval_context=retrieval_context,
    )

    # One evaluate() call per golden (test_cases=[test_case], never the
    # whole GOLDENS list) — keeps scoring per-golden and gives each a
    # clean row (or rows, one per metric) in REPORT_CSV. fallback_index=index
    # is what makes golden_id unique per row (e.g. "p1_0" vs "p1_1") instead
    # of every golden sharing the same priority-only id.
    result = evaluate_golden(
        golden, test_case, RAG_METRICS, csv_path=REPORT_CSV, fallback_index=index
    )
    assert result.success, f"{result.name} failed — see {REPORT_CSV} for per-metric scores"