"""
Generated by `elyaeval init --task-type rag_qa` (existing-corpus mode, the default).

This file is yours to edit — it is a starting point, not a managed
artifact. Everything below calls DeepEval's own API directly (evaluate,
LLMTestCase, Golden). ElyaEval supplied the dataset-loading helper and the
metric preset.

EXISTING-CORPUS mode: this suite assumes the RAG demo's corpus already has
what it needs (see ingest.py / sample_docs), so it just calls the real pipeline and lets
it retrieve for real. Nothing is inserted into or deleted from Postgres —
no ingest/teardown fixture.

GOLDENS come from goldens_rag_demo.jsonl, written
against that same corpus — NOT the bundled generic standard dataset, that this corpus can't answer.

If you ever need to run the shared standard dataset against a corpus that
doesn't already cover it, regenerate with:
    elyaeval init --task-type rag_qa --corpus-mode seeded
That variant seeds each golden's context passages in before the run and
tears them down after — this file intentionally does not.

--- HTTP-decoupled edit ---
run_app() now calls the SUT's /query endpoint over HTTP (see app.py)
instead of importing rag_core directly. This file no longer imports
anything from the RAG demo's own package — it only knows RAG_APP_URL
and the {"answer", "retrieval_context"} JSON contract. That's what lets
a CI recipe run this suite without knowing pgvector/Ollama/etc. exist.

RAG_APP_URL must be reachable from wherever this test process actually
runs (your shell, or the CI runner's pod/container) — not just from your
laptop. See the Tekton recipe notes for what that means on a kind
cluster.
"""

import os

import requests
from deepeval import assert_test
from deepeval.test_case import LLMTestCase
import pytest

from elyaeval import load_standard_dataset
from elyaeval.metrics import RAG_METRICS

RAG_APP_URL = os.environ["RAG_APP_URL"].rstrip("/")


def run_app(user_input: str, expected_output: str | None = None) -> tuple[str, list[str]]:
    """Call the SUT's /query endpoint; the app retrieves from its own corpus."""
    response = requests.post(
        f"{RAG_APP_URL}/query",
        json={"query": user_input, "expected_output": expected_output},
        timeout=60,
    )
    response.raise_for_status()
    result = response.json()
    return result["answer"], result["retrieval_context"]


GOLDENS = load_standard_dataset(
    task_type="rag_qa",
    ci_stage="nightly",
    dataset_path="goldens_rag_demo.jsonl",
)


@pytest.mark.parametrize(
    "golden",
    GOLDENS,
    ids=[g.additional_metadata.get("priority", "") + "_" + str(i) for i, g in enumerate(GOLDENS)],
)
def test_rag_qa(golden):
    actual_output, retrieval_context = run_app(golden.input, expected_output=golden.expected_output)

    test_case = LLMTestCase(
        input=golden.input,
        actual_output=actual_output,
        expected_output=golden.expected_output,
        context=golden.context,
        retrieval_context=retrieval_context,
    )

    assert_test(test_case, RAG_METRICS)