"""
Generated by `elyaeval init --task-type rag_qa --eval-mode component`.

This file is yours to edit — it is a starting point, not a managed
artifact. Like the e2e template, this calls DeepEval's own API directly
(EvaluationDataset, evals_iterator). ElyaEval supplied the dataset and the
CSV-reporting glue (elyaeval.tracing_report).

This suite imports your app's traced entrypoint DIRECTLY (no HTTP) and drives it through
DeepEval's evals_iterator(), which walks every @observe'd span your app
declared metrics on (e.g. a retrieve span, a generate_answer span) and
scores each one separately. Both suites are meant to run side by side in
CI, not replace one another — this one tells you WHICH stage regressed;
the e2e one tells you whether the app's final answer is still good.

Requirements on the SUT side for this to produce anything:
  - the traced entrypoint function (imported below) must be decorated
    with @observe (or wrap internal calls that are)
  - each span you want scored must declare its own metrics via
    @observe(metrics=[...]) and call update_current_span(test_case=...)
    inside that function — this file does NOT pass span-level metrics in;
    it only reads back whatever the SUT already attached.
  - if the entrypoint itself has metrics=[...] (an outer @observe, not
    just its children), an aggregate/end-to-end-style score is possible
    here too, but that's optional and off by default (TRACE_METRICS below).

WHAT YOU NEED TO FILL IN (search for TODO):
  1. Import your app's traced entrypoint function (in-process, not HTTP).
  2. Implement call_sut() to invoke it for one golden.

REPORT_CSV: one row per (golden, span, metric) triple, written to a
SEPARATE csv from the e2e suite's REPORT_CSV — same append-as-you-go
convention, but with an extra span_name column so you can see which stage
(e.g. "retrieve" vs "generate_answer") a given score belongs to. Point it
at wherever your CI workspace collects reports; it defaults to a local
report/ dir for running the suite by hand.
"""

from pathlib import Path

from deepeval.dataset import Golden
import pytest

from elyaeval import load_standard_dataset
from elyaeval.tracing_report import TracedRunner, golden_id, append_traced_csv_rows, traced_test_result_to_csv_rows

REPORT_CSV = Path("report/results_rag_qa_component.csv")

# TODO 1: import your app's traced entrypoint, in-process, e.g.:
from rag_core import run_for_eval

# Trace-level metrics (evaluated against the WHOLE call, not any one span).
# Leave empty unless your entrypoint's own @observe() declares metrics=[...]
# and calls update_current_trace(input=..., actual_output=...) — most SUTs
# only score at the span level (retrieve/generate_answer), so this is []
# by default and every CSV row comes from span-level metrics instead.
TRACE_METRICS = []


def call_sut(golden: Golden) -> None:
    run_for_eval(golden.input, expected_output=golden.expected_output)
    """
    TODO 2: call your app's traced entrypoint here, in-process.

    Must be a plain call that runs your app for `golden.input` — nothing
    needs to be returned. DeepEval reads the SUT's output back off the
    span/trace it recorded via @observe + update_current_span/
    update_current_trace, not off this function's return value.

    e.g.:
        def call_sut(golden):
            run_for_eval(golden.input, expected_output=golden.expected_output)

    This MUST be an in-process import + call (see module docstring for
    why) — there is no HTTP equivalent for this template, unlike
    test_elyaeval_rag_qa.py's run_app().
    """
    
    


GOLDENS = load_standard_dataset(
    task_type="rag_qa", ci_stage="nightly",
    dataset_path="goldens_rag_demo.jsonl",
)


@pytest.mark.parametrize(
    "indexed_golden",
    list(enumerate(GOLDENS)),
    ids=[g.additional_metadata.get("priority", "") + "_" + str(i) for i, g in enumerate(GOLDENS)],
)
def test_rag_qa_component(indexed_golden):
    index, golden = indexed_golden

    # A fresh single-golden EvaluationDataset per test — never one
    # evals_iterator() call batched over the whole GOLDENS list — so this
    # stays one pytest test per golden, one CSV append per golden, exactly
    # like the e2e template's one evaluate_golden() call per golden.
    result = TracedRunner(golden, metrics=TRACE_METRICS).run(call_sut)

    gid = golden_id(golden, fallback_index=index)
    priority = (golden.additional_metadata or {}).get("priority", "")

    rows = []
    for test_result in result.test_results:
        rows.extend(traced_test_result_to_csv_rows(gid, priority, test_result))
    append_traced_csv_rows(REPORT_CSV, rows)

    failed = [tr.name for tr in result.test_results if not tr.success]
    assert not failed, f"span(s) failed: {failed} — see {REPORT_CSV} for per-metric scores"
